### ISSUE TITLE
/fdmds Command

### ISSUE THREAD

**Issue by MatitoDA** [SlimeCloud/java-SlimeBot#10]
## Frag doch mal den Slime

**Befehl**
`/fdmds <frage>`

Frage wird genommen und in einen Channel geschickt, user bekommt Feedback nach erfolgreichem Senden

**Comment by Byteingpython** [comment]
> ## Frag doch mal den Slime
> 
> **Befehl**
> `/fdmds <frage>`
> 
> Frage wird genommen und in einen Channel geschickt, user bekommt Feedback nach erfolgreichem Senden

Dann müssten die user aber entweder die Fragen immer im gleichen Format stellen, oder man macht aus dem Command /fdms <frage> <antwort> <antwort> <antwort>...
