### ISSUE TITLE
Birthdays

### ISSUE THREAD

**Issue by MatitoDev** [SlimeCloud/java-SlimeBot#100]
Transfer the current data
if this is not possible, we have to lost the old data ([its ok for the Members](https://discord.com/channels/1077255218728796192/1077257287850283099/1145428291143077918))

- [x] /birthday {target}   no target -> author   -> shows the birthday of the target user
- [ ] /next-birthdays shows the next 10 birthdays
- [ ] /remember-birthday {day} {month} [optional]{year} Add the specified birthday to the system (if the user is already in the system, the existing entry will be overwritten)
- [ ] /forget-brithday rremove the author's birthday from the system

**Comment by cyklon73** [comment]
suggestion: what do you think if the bot pings the people in the main chat every day who have a birthday on that day with a little message? then the birthday thing would make a bit more sense

**Comment by MatitoDev** [comment]
> suggestion: what do you think if the bot pings the people in the main chat every day who have a birthday on that day with a little message? then the birthday thing would make a bit more sense
?
![image](https://github.com/SlimeCloud/java-SlimeBot/assets/77804268/8bf3e723-c77a-4b62-8406-fc1d76b86486)
