### ISSUE TITLE
Leaderboard not ephemeral

### ISSUE THREAD

**Issue by MineKing9534** [SlimeCloud/java-SlimeBot#134]
**Is your feature request related to a problem? Please describe.**
Don't make the leaderboard command response ephemeral but visible for everyone.

**Additional context**
Requested by user on discord (see https://discord.com/channels/1077255218728796192/1077261949357797386/1157819821417828533)

**Comment by cyklon73** [comment]
We discussed for a long time whether we should do it that way and there were reasons why we did it that way. summarized here again: https://discord.com/channels/1077255218728796192/1077261949357797386/1157959353144455178
