### ISSUE TITLE
/setup command

### ISSUE THREAD

**Issue by MatitoDA** [SlimeCloud/java-SlimeBot#16]
**Is your feature request related to a problem? Please describe.**
You have to change to join every config value alone

**Describe the solution you'd like**
A command that guides the User through this process
You go through multiple embeds, for each value in the Config
- Staff Role: A Message like "Set a Staff-Role." with 3 Btn (choose Role, Create Role, Skip)
- verify role; A Message like "set a Verify role" with 3 Btn (choose Role, Create Role, Skip)
- same for every Channel and Role in the config.yml

**Additional context**
at the color choice, maybe link to a color wheel which outputs RGB values

**Comment by Byteingpython** [comment]
Wäre praktisch wenn man ein Interface/Eine abstrakte Klasse einführen würde, und diese dann für verschiedene Typen erweitert. Dann könnte man bei einem Manager alle Parameter zusammen mit der zugehörigen Subclass registrieren.
Es einfach so hardcoden wäre nämlich meiner Meinung nach keine gute Idee, da der Wartungsaufwand für dieses Hardgecodete dann einfach zu hoch wäre.
