### ISSUE TITLE
Anstatt Config.java lieber .env nutzen

### ISSUE THREAD

**Issue by Root-Time** [SlimeCloud/java-SlimeBot#25]
Ist nur ein kleiner Vorschlag anstatt das ihr den Token von utils/Config.java benutzt und immer bei einem Config.java updatet ihn manuell entfernen müsst nutzt lieber eine ".env" File. Die wäre dann im resources Ordner

Ein weitere Vorteil jeder kann den Bot mit seinen eigenen Bot bzw. später auch eigene Datenbank testen und es ist sicher.

Mit dieser Dependency könnt ihr sie dann auch lesen:
https://github.com/cdimascio/dotenv-java

Ihr müsst dann die File im .gitignore rein machen

**Comment by Byteingpython** [comment]
Dann könnte man auch einfacher dinge wie automatisches Testen und automatischen upload auf den Host machen
