### ISSUE TITLE
Notifikation wenn ein neues gamingguidesde Video online kommt

### ISSUE THREAD

**Issue by Root-Time** [SlimeCloud/java-SlimeBot#27]
**Is your feature request related to a problem? Please describe.**
Die YouTube Notifikationen sind ja oft nicht an bzw. man bekommt keine Benachrichtigung. Dann wäre es doch gut wenn man sie beim Discord Server bekommt.  

**Describe the solution you'd like**
Einen Channel erstellen der immer ein Notifikation postet wenn ein neues Video online kommt und die Leute pingt die die Social Role haben.

**Describe alternatives you've considered**
//

**Additional context**
//

**Comment by Byteingpython** [comment]
Gibt es dass nicht schon??

**Comment by Uguralg3a** [comment]
Sowas gibt's schon ^^

**Comment by Root-Time** [comment]
Auf dem SlimeCloud Server?

**Comment by MatitoDA** [comment]
Bereits über Mee6 geregelt: [->Social Media -> #announcement](https://discord.com/channels/1077255218728796192/1110291627865542677/1122904610965819502)

**Comment by Root-Time** [comment]
Also wollen wir nicht bereits vorhandene Features von anderen Bot nicht selbst nochmal machen?
@MatitoDA

**Comment by MatitoDA** [comment]
Don't change a running system xd
