### ISSUE TITLE
Code Struktur wechseln von Events/Commands zu Modul System

### ISSUE THREAD

**Issue by Root-Time** [SlimeCloud/java-SlimeBot#29]
**Problem**
Aktuell ist es ja gerade so das der Code in Events und Commands unterteilt ist. An sich ist das gut bei Bots mit einem spezifischen Feature. Dazu kommt noch das man später viele Switch Case Statement hat um die einzelnen Features im Event zu differenzieren. 

**Lösung**
Ein Module System ist da besser geeignet, da oft mehrere gleiche Events für verschiedene Module gebraucht werden.
Später kann es dann nämlich zu Problem bei der Organisation geben bzw. auch bei Benennung. 

**Aufbau**
- module/
    - voice_temp/
        - OnJoin.java ("Auch wenn das auf einen anderen Event hindeutet ist dennoch klar da im VoiceTemp Ordner ist")
        - OnLeave.java 
        - Handler.java
    - notification/
        - ...
        
**Bedingung**
Also nur wenn ihr plant einige verschiedene Features hinzuzufügen.

**Comment by MatitoDA** [comment]
ich denke das ist etwas überflüssig
