### ISSUE TITLE
Automatisierte Tests im Repo

### ISSUE THREAD

**Issue by Byteingpython** [SlimeCloud/java-SlimeBot#33]
**Describe the solution you'd like**
Irgendwas, wie zb. Deepsource, das automatisch bei jedem Pull Request und Commit den Code auf Fehler oder anitpatterns untersucht, um Fehler in der Codebase vorzubeugen

**Describe alternatives you've considered**
Einfach nur händisch drüberkucken

**Comment by MineKing9534** [comment]
Braucht man das wirklich? Weil gereviwed werden muss das zeug so oder so manuell. Ne GitHub action die schaut obs compiler probleme gibt könnte man aber echt machen...

**Comment by Byteingpython** [comment]
> Braucht man das wirklich? Weil gereviwed werden muss das zeug so oder so manuell. Ne GitHub action die schaut obs compiler probleme gibt könnte man aber echt machen...

Ja, weil solche automatisierten tests den code nicht auf bugs in der Funktion, wie unsere manuellen tests, sondern auf antipatterns, die meist nicht einfach erkenntlich sind, und Sicherheitsbugs, die auch meist nicht mit einem einfachen lesen zu finden sind. Diese antipatterns und sicherheitsbugs würden dafür sorgen, dass die codebase immer schwieriger zu verstehen wird, einen sehr hohen wartungsaufwand verursachen und den code unsicher machen

**Comment by Byteingpython** [comment]
Man könnte damit auch den code direkt formatieren lassen

**Comment by MineKing9534** [comment]
Ka gut, macht sinn

**Comment by MatitoDA** [comment]
I have added [DeepSource](https://app.deepsource.com/gh/SlimeCloud/java-SlimeBot/issues?category=recommended&page=1) and Merged #85
