### ISSUE TITLE
Disable/Enable Features

### ISSUE THREAD

**Issue by MatitoDA** [SlimeCloud/java-SlimeBot#49]
**Is your feature request related to a problem? Please describe.**
at the first start, we have many errors coming from missing configurations.

**Describe the solution you'd like**
a config key with which you can enable or disable a feature

**features which should have this option:**
- [ ] Podcast notify
- [ ] Album notify
- [ ] fdmds

for features like logging, holidays greetings etc. no message should be sent if the channel id is 0 (default)

**Comment by MineKing9534** [comment]
When both #47 and #46 are merged, this is very easy for Fdmds by just disabling the command. The command handler used in #47 has a feature to bind commands being added only if a condition is fulfilled. 
For podcast/spotify notifications we can just create a new channel configuration for these notifications and also apply the `id=0 => don't send any messages` strategy.
