### ISSUE TITLE
Welcome and Goodbye Message

### ISSUE THREAD

**Issue by MatitoDA** [SlimeCloud/java-SlimeBot#94]
Automatically sends a message to new members or when someone leaves the server.

- [ ] set channel
- [ ] message
- [ ] image
current image, but you can design some. Maybe we can ask the community for a design
![image](https://github.com/SlimeCloud/java-SlimeBot/assets/77804268/7234d7b1-0b16-4c83-9c82-8d075bd16a6c)

**Comment by Byteingpython** [comment]
We could try to adapt the style of the holiday alert [Image](https://cdn.discordapp.com/attachments/1098707158750724186/1125467211847454781/Slimeferien.png)

**Comment by MatitoDA** [comment]
Es wurde sich dazu entschieden, nur noch die Join Nachrichten von Discord selbst zu nutzen
https://discord.com/channels/1077255218728796192/1077256567780540476/1150511087289122940
